// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pe} from '../models';

export function GenerateCmakeProject(arg1:string,arg2:string,arg3:Array<number>):Promise<void>;

export function GetExportInfo(arg1:string):Promise<Array<pe.ExportFunction>>;

export function Greet(arg1:string):Promise<string>;

export function SelectInputFile():Promise<string>;

export function SelectOutputDirectory():Promise<string>;
