// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCmakeProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateCmakeProject'](arg1, arg2, arg3);
}

export function GetExportInfo(arg1) {
  return window['go']['main']['App']['GetExportInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
